FROM 17710472946/centos_nginx_php:v2
MAINTAINER 17710472946@163.com
ADD docker_entrypoint.sh /usr/local/bin/docker_entrypoint.sh
RUN chmod a+x /usr/local/bin/docker_entrypoint.sh
CMD ["/usr/local/bin/docker_entrypoint.sh"]